package com.sgv.demo.model;

public class Asignacion_reporte {
	
	String id_asignacion;
	long id_reporte;
	String fecha_reporte;
	String descripcion;

	public Asignacion_reporte() {
	}

	public Asignacion_reporte(String id_asignacion, long id_reporte, String fecha_reporte, String descripcion) {
		this.id_asignacion = id_asignacion;
		this.id_reporte = id_reporte;
		this.fecha_reporte = fecha_reporte;
		this.descripcion = descripcion;
	}

	public String getId_asignacion() {
		return id_asignacion;
	}

	public void setId_asignacion(String id_asignacion) {
		this.id_asignacion = id_asignacion;
	}

	public long getId_reporte() {
		return id_reporte;
	}

	public void setId_reporte(long id_reporte) {
		this.id_reporte = id_reporte;
	}

	public String getFecha_reporte() {
		return fecha_reporte;
	}

	public void setFecha_reporte(String fecha_reporte) {
		this.fecha_reporte = fecha_reporte;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}

/*
 * CREATE TABLE TB_REPORTES ( "id_asignacion" VARCHAR2(7) NOT NULL REFERENCES
 * TB_ASIGNACION, "id_report" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1
 * MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCYCLE NOT
 * NULL, "fecha_report" DATE NOT NULL, "descripcion" VARCHAR2(1000), PRIMARY KEY
 * ("id_asignacion", "id_report") );
 */
