package com.sgv.demo.model;

public class Asignacion_reporte {

}

/*
     CREATE TABLE TB_REPORTES
    (
    "id_asignacion" VARCHAR2(7) NOT NULL REFERENCES TB_ASIGNACION, 
	"id_report" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1  NOCYCLE NOT NULL, 
	"fecha_report" DATE NOT NULL, 
	"descripcion" VARCHAR2(1000), 
	 PRIMARY KEY ("id_asignacion", "id_report")
     );
 * */
 