package com.sgv.demo.model;

public class Averia_Historial {

}
/**
 * 
  CREATE TABLE tb_averia_historial (
      "detalle" NUMBER  GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1 ,
      "id_historial" VARCHAR2(7) NOT NULL REFERENCES TB_historial_vehiculo,
      "id_averia" NUMBER NOT NULL REFERENCES tb_averia,
      PRIMARY KEY("detalle","id_historial")
    );
 * */
 