package com.sgv.demo.model;

public class Boleta_Historial {
	private long detalle;
	private String id_historial;
	private String id_boleta;

	public Boleta_Historial(long detalle, String id_historial, String id_boleta) {
		this.detalle = detalle;
		this.id_historial = id_historial;
		this.id_boleta = id_boleta;
	}

	public Boleta_Historial() {
	}

	public long getDetalle() {
		return detalle;
	}

	public void setDetalle(long detalle) {
		this.detalle = detalle;
	}

	public String getId_historial() {
		return id_historial;
	}

	public void setId_historial(String id_historial) {
		this.id_historial = id_historial;
	}

	public String getId_boleta() {
		return id_boleta;
	}

	public void setId_boleta(String id_boleta) {
		this.id_boleta = id_boleta;
	}

}
/*
 * CREATE TABLE tb_boleta_historial( "detalle" NUMBER GENERATED BY DEFAULT ON
 * NULL AS IDENTITY START WITH 1 INCREMENT BY 1 , "id_historial" varchar2(10)
 * NOT NULL REFERENCES TB_HISTORIAL_PAGOS, "id_boleta" VARCHAR2(8) NOT NULL
 * REFERENCES TB_BOLETA, PRIMARY KEY("detalle","id_historial","id_boleta") );
 */
