package com.sgv.demo.model;

public class Boleta_Historial {

}
/*
 *     CREATE TABLE tb_boleta_historial(
      "detalle" NUMBER  GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1 ,
      "id_historial" varchar2(10) NOT NULL REFERENCES TB_HISTORIAL_PAGOS,
      "id_boleta"    VARCHAR2(8) NOT NULL REFERENCES TB_BOLETA,
      PRIMARY KEY("detalle","id_historial","id_boleta")
    );
 * */
 