package com.sgv.demo.model;

public class Contrato {
	
	private long id_contrato;
	private String id_asignacion;
	private double AFP;
	private double CTS;
	private double Asignacion_fam;
	private double salario;
	private String modalidad_cont;
	private int tiempo_cont;
	private String detalle_cont;
	public long getId_contrato() {
		return id_contrato;
	}
	public void setId_contrato(long id_contrato) {
		this.id_contrato = id_contrato;
	}
	public String getId_asignacion() {
		return id_asignacion;
	}
	public void setId_asignacion(String id_asignacion) {
		this.id_asignacion = id_asignacion;
	}
	public double getAFP() {
		return AFP;
	}
	public void setAFP(double aFP) {
		AFP = aFP;
	}
	public double getCTS() {
		return CTS;
	}
	public void setCTS(double cTS) {
		CTS = cTS;
	}
	public double getAsignacion_fam() {
		return Asignacion_fam;
	}
	public void setAsignacion_fam(double asignacion_fam) {
		Asignacion_fam = asignacion_fam;
	}
	public double getSalario() {
		return salario;
	}
	public void setSalario(double salario) {
		this.salario = salario;
	}
	public String getModalidad_cont() {
		return modalidad_cont;
	}
	public void setModalidad_cont(String modalidad_cont) {
		this.modalidad_cont = modalidad_cont;
	}
	public int getTiempo_cont() {
		return tiempo_cont;
	}
	public void setTiempo_cont(int tiempo_cont) {
		this.tiempo_cont = tiempo_cont;
	}
	public String getDetalle_cont() {
		return detalle_cont;
	}
	public void setDetalle_cont(String detalle_cont) {
		this.detalle_cont = detalle_cont;
	}
	public Contrato(long id_contrato, String id_asignacion, double aFP, double cTS, double asignacion_fam,
			double salario, String modalidad_cont, int tiempo_cont, String detalle_cont) {
		super();
		this.id_contrato = id_contrato;
		this.id_asignacion = id_asignacion;
		AFP = aFP;
		CTS = cTS;
		Asignacion_fam = asignacion_fam;
		this.salario = salario;
		this.modalidad_cont = modalidad_cont;
		this.tiempo_cont = tiempo_cont;
		this.detalle_cont = detalle_cont;
	}
	public Contrato() {
		// TODO Auto-generated constructor stub
	}
	



}
/*
     CREATE TABLE TB_CONTRATO(
      "id_contrato" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 3150000000 MAXVALUE 9999999999 INCREMENT BY 1  PRIMARY KEY,
      "id_asignacion" VARCHAR2(7) NOT NULL REFERENCES TB_ASIGNACION,
    "AFP" NUMBER(6,2) NOT NULL,
      "CTS" NUMBER(6,2) NOT NULL,
      "Asignacion_fam" NUMBER(6,2),
      "salario" NUMBER(10,2) NOT NULL,
      "modalidad_cont" VARCHAR2(150),
      "tiempo_cont" NUMBER NOT NULL, --MESES
      "detalle_cont" VARCHAR2(250) NULL
     );
 * 
 */
