package com.sgv.demo.model;

public class Especificacion {

}

/*
    CREATE TABLE tb_especificaciones (
      "id_espec" NUMBER  GENERATED BY DEFAULT AS IDENTITY START WITH  1 INCREMENT BY 1 PRIMARY KEY,
      "des_espec" VARCHAR2(150)
      ); 
 * */
 