package com.sgv.demo.model;

public class Especificacion {

	private long id_espec;
	private String des_espec;

	public Especificacion(long id_espec, String des_espec) {
		this.id_espec = id_espec;
		this.des_espec = des_espec;
	}

	public Especificacion() {
	}

	public long getId_espec() {
		return id_espec;
	}

	public void setId_espec(long id_espec) {
		this.id_espec = id_espec;
	}

	public String getDes_espec() {
		return des_espec;
	}

	public void setDes_espec(String des_espec) {
		this.des_espec = des_espec;
	}

}

/*
 * CREATE TABLE tb_especificaciones ( "id_espec" NUMBER GENERATED BY DEFAULT AS
 * IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY, "des_espec" VARCHAR2(150)
 * );
 */
