package com.sgv.demo.model;

public class Mantenimiento_Especif {
	
	private long detalle;
	private long id_mant;
	private long id_espec;

	public Mantenimiento_Especif(long detalle, long id_mant, long id_espec) {
		this.detalle = detalle;
		this.id_mant = id_mant;
		this.id_espec = id_espec;
	}

	public Mantenimiento_Especif() {
	}

	public long getDetalle() {
		return detalle;
	}

	public void setDetalle(long detalle) {
		this.detalle = detalle;
	}

	public long getId_mant() {
		return id_mant;
	}

	public void setId_mant(long id_mant) {
		this.id_mant = id_mant;
	}

	public long getId_espec() {
		return id_espec;
	}

	public void setId_espec(long id_espec) {
		this.id_espec = id_espec;
	}

}
/**
 * --TABLA MANTENIMIENTO - ESPECIFICACION DROP TABLE tb_mantenimiento_espec;
 * CREATE TABLE tb_mantenimiento_espec ( "detalle" NUMBER GENERATED BY DEFAULT
 * AS IDENTITY START WITH 1 INCREMENT BY 1, "id_mant" NUMBER REFERENCES
 * tb_mantenimiento, "id_espec" NUMBER REFERENCES tb_especificaciones, PRIMARY
 * KEY("detalle","id_mant") );
 */