package com.sgv.demo.model;

public class Mantenimiento_Especif {

}
/**
    --TABLA MANTENIMIENTO - ESPECIFICACION
    DROP TABLE tb_mantenimiento_espec;
    CREATE TABLE tb_mantenimiento_espec (
      "detalle" NUMBER  GENERATED BY DEFAULT AS IDENTITY START WITH  1 INCREMENT BY 1,
      "id_mant" NUMBER REFERENCES tb_mantenimiento,
      "id_espec" NUMBER REFERENCES tb_especificaciones,
      PRIMARY KEY("detalle","id_mant")
    );
*/