package com.sgv.demo.model;

public class Mantenimiento_Historial {

	private long detalle;
	private String id_historial;
	private long id_mant;

	public Mantenimiento_Historial(long detalle, String id_historial, long id_mant) {
		this.detalle = detalle;
		this.id_historial = id_historial;
		this.id_mant = id_mant;
	}

	public Mantenimiento_Historial() {
	}

	public long getDetalle() {
		return detalle;
	}

	public void setDetalle(long detalle) {
		this.detalle = detalle;
	}

	public String getId_historial() {
		return id_historial;
	}

	public void setId_historial(String id_historial) {
		this.id_historial = id_historial;
	}

	public long getId_mant() {
		return id_mant;
	}

	public void setId_mant(long id_mant) {
		this.id_mant = id_mant;
	}

}
/*
	CREATE TABLE tb_mantenimiento_historial (
	  "detalle" NUMBER  GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1 ,
	  "id_historial" VARCHAR2(7) NOT NULL REFERENCES TB_historial_vehiculo,
	  "id_mant" NUMBER REFERENCES tb_mantenimiento,
	  PRIMARY KEY("detalle","id_historial","id_mant")
	);
 
 * */
 