package com.sgv.demo.model;

public class Mantenimiento {

}
/**
 *  CREATE TABLE tb_mantenimiento(
      "id_mant" NUMBER  GENERATED BY DEFAULT AS IDENTITY MINVALUE 10001 MAXVALUE 99999 INCREMENT BY 1 PRIMARY KEY,
      "nom_evaluador" VARCHAR(50) NOT NULL,
      "eva_preliminar" VARCHAR(500) NOT NULL,
      "diagnostico" VARCHAR(500) NOT NULL,
      "observaciones" VARCHAR(500) NOT NULL,
      "fecha_mant" DATE,
      "prox_fecha" DATE
    );
 * */
 