package com.sgv.demo.model;

public class Mantenimiento_Historial {

}
/*
	CREATE TABLE tb_mantenimiento_historial (
	  "detalle" NUMBER  GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1 INCREMENT BY 1 ,
	  "id_historial" VARCHAR2(7) NOT NULL REFERENCES TB_historial_vehiculo,
	  "id_mant" NUMBER REFERENCES tb_mantenimiento,
	  PRIMARY KEY("detalle","id_historial","id_mant")
	);
 
 * */
 